---
name: Android CI

on:
  push:
    paths-ignore:
      - LICENSE
      - README.md
      - SECURITY.md
      - CODE_OF_CONDUCT.md
      - .github/workflows/*
      - .github/ISSUE_TEMPLATE/*
      - fastlane/*
  pull_request:
    path-ignore:
      - LICENSE
      - README.md
      - SECURITY.md
      - CODE_OF_CONDUCT.md
      - .github/workflows/*
      - .github/ISSUE_TEMPLATE/*
      - fastlane/*
  workflow_dispatch:

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up JDK 18
        uses: actions/setup-java@v3.5.0
        with:
          distribution: 'temurin'
          java-version: '18'

      - name: Give permission to executable
        run: chmod +x gradlew

      - name: Build with gradle
        uses: gradle/gradle-build-action@v2.3.0
        with:
          arguments: assembleDebug

      - name: Upload debug apk
        uses: actions/upload-artifact@v3
        with:
          name: apk-debug
          path: app/build/outputs/apk/debug/app-debug.apk
