name: Android CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up JDK 17
        uses: actions/setup-java@v4.2.0
        with:
          distribution: 'temurin'
          java-version: '17'

      - name: Give permission to executable
        run: chmod +x gradlew

      - name: Build with gradle
        uses: gradle/gradle-build-action@v3.1.0
        with:
          gradle-version: nightly
          arguments: assembleDebug

      - name: Upload debug apks
        uses: actions/upload-artifact@v4
        with:
          name: app-arm64-v8a
          path: app/build/outputs/apk/dev/debug/app-dev-arm64-v8a-debug.apk

      - uses: actions/upload-artifact@v4
        with:
          name: app-armeabi-v7a
          path: app/build/outputs/apk/dev/debug/app-dev-armeabi-v7a-debug.apk

      - uses: actions/upload-artifact@v4
        with:
          name: app-x86
          path: app/build/outputs/apk/dev/debug/app-dev-x86-debug.apk

      - uses: actions/upload-artifact@v4
        with:
          name: app-x86_64
          path: app/build/outputs/apk/dev/debug/app-dev-x86_64-debug.apk

      - uses: actions/upload-artifact@v4
        with:
          name: app-universal
          path: app/build/outputs/apk/dev/debug/app-dev-universal-debug.apk
