---
name: 'Java Code Formatter'

on:
  workflow_dispatch:

jobs:

  formatting:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3.0.2
      - uses: axel-op/googlejavaformat-action@v3.6.0
        with:
          args: "--aosp --replace"
          commitMessage: "Format Java Code"
