name: Update Gradle Wrapper

on:
  workflow_dispatch:
---

jobs:
  update_wrapper:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: set up JDK 17
        uses: actions/setup-java@v2
        with:
          java-version: '17'
          distribution: 'temurin'

      - name: Grant execute permission for gradlew
        run: chmod +x gradlew

      - name: Update gradle wrapper
        uses: gradle/gradle-build-action@v2
        with:
          arguments: |
              wrapper
              --gradle-version
              ${{ secrets.GRADLE_VERSION }}

      - name: Add updated files to stage
        run: git add --all

      - name: Setup email
        run: git config --global user.email "${{ secrets.EMAIL }}"

      - name: Setup name
        run: git config --global user.name "Gradle Wrapper"

      - name: Commit latest gradle wrapper
        run: git commit -m "Update gradle wrapper to v${{ secrets.GRADLE_VERSION }}"

      - name: Push all changes
        run: git push
